"""Ajout prenom et telephone a User

Revision ID: 3190d04f5201
Revises: d9c37e664252
Create Date: 2026-05-09 16:08:19.503984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3190d04f5201'
down_revision = 'd9c37e664252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prenom', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('telephone')
        batch_op.drop_column('prenom')

    # ### end Alembic commands ###
