"""fix foreign key reponses_client to investigations

Revision ID: 33eaa4876c68
Revises: 
Create Date: 2026-04-23 20:18:19.333308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eaa4876c68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('ville', sa.String(length=50), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=256), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=50), nullable=True),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('transaction_hour', sa.Integer(), nullable=True),
    sa.Column('date_transaction', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('device_trust_score', sa.Float(), nullable=True),
    sa.Column('velocity_last_24h', sa.Integer(), nullable=True),
    sa.Column('cardholder_age', sa.Integer(), nullable=True),
    sa.Column('foreign_transaction', sa.Integer(), nullable=True),
    sa.Column('location_mismatch', sa.Integer(), nullable=True),
    sa.Column('merchant_category', sa.String(length=50), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('alert_signals', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    op.create_table('decisions_humaines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('date_decision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fraudes_detectees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('date_detection', sa.DateTime(), nullable=True),
    sa.Column('confirme_par_agent', sa.Boolean(), nullable=True),
    sa.Column('confirme_par_client', sa.Boolean(), nullable=True),
    sa.Column('type_fraude', sa.String(length=50), nullable=True),
    sa.Column('montant_fraude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('statut_inv', sa.String(length=30), nullable=True),
    sa.Column('reponse_client', sa.String(length=20), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id_investigation'),
    sa.UniqueConstraint('token')
    )
    op.create_table('notifications_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_transaction', sa.Integer(), nullable=True),
    sa.Column('type_notif', sa.String(length=50), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=True),
    sa.Column('statut_envoi', sa.String(length=20), nullable=True),
    sa.Column('date_envoi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reponses_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_investigation', sa.Integer(), nullable=False),
    sa.Column('reponse', sa.String(length=20), nullable=True),
    sa.Column('date_reponse', sa.DateTime(), nullable=True),
    sa.Column('ip_client', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_investigation'], ['investigations.id_investigation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reponses_client')
    op.drop_table('notifications_client')
    op.drop_table('investigations')
    op.drop_table('fraudes_detectees')
    op.drop_table('decisions_humaines')
    op.drop_table('transactions')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
