"""ajout colonne actif dans users

Revision ID: 8958753b4c6f
Revises: 90280066335f
Create Date: 2026-04-24 23:41:34.627736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8958753b4c6f'
down_revision = '90280066335f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actif', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('actif')

    # ### end Alembic commands ###
