"""ajout de la colonne age dans user

Revision ID: 90280066335f
Revises: 33eaa4876c68
Create Date: 2026-04-24 23:25:08.981165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90280066335f'
down_revision = '33eaa4876c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('actif')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actif', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
