"""add dark_mode and language to users

Revision ID: 9a4d2abe2479
Revises: ee08df0d3d97
Create Date: 2026-05-11 04:41:03.267386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4d2abe2479'
down_revision = 'ee08df0d3d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('language')
        batch_op.drop_column('dark_mode')

    # ### end Alembic commands ###
