"""Suppression NotificationClient, ajout email_envoye et date_envoi_email dans Investigation

Revision ID: d9c37e664252
Revises: 8958753b4c6f
Create Date: 2026-05-05 14:56:28.322829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c37e664252'
down_revision = '8958753b4c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications_client')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_envoye', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_envoi_email', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_column('date_envoi_email')
        batch_op.drop_column('email_envoye')

    op.create_table('notifications_client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_client', sa.INTEGER(), nullable=False),
    sa.Column('id_transaction', sa.INTEGER(), nullable=True),
    sa.Column('type_notif', sa.VARCHAR(length=50), nullable=True),
    sa.Column('canal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('statut_envoi', sa.VARCHAR(length=20), nullable=True),
    sa.Column('date_envoi', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.ForeignKeyConstraint(['id_transaction'], ['transactions.id_transaction'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
