"""ajout preferences_json totp_secret totp_enabled

Revision ID: ee08df0d3d97
Revises: 3190d04f5201
Create Date: 2026-05-11 03:02:51.492930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee08df0d3d97'
down_revision = '3190d04f5201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('risk_medium', sa.Float(), nullable=False),
    sa.Column('risk_high', sa.Float(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threshold_history')
    # ### end Alembic commands ###
